{
  "assai": {
    "suinco": [
      "Picanha Temperada Resfriada Suinco",
      "Barriga Temperada Resfriada Suinco",
      "Fraldinha Temperada Resfriada Suinco",
      "Sobrepaleta Temperado Resfriado Suinco",
      "Pernil Temperado Resfriado Suinco",
      "File Mignon Temperado Resfriada Suinco",
      "Linguiça Petisco Suinco",
      "Esbein Joelho Suinco",
      "Lombo Temperado Resfriado Suinco",
      "Bacon Em Cubos Suinco",
      "Bacon Suinco",
      "Bacon Fatiado Suinco 500g",
      "Costela Temperada Resfriada Suinco",
      "Alcatra Temperada Resfriada Suinco"
    ],
    "original": [
      "Morango 1,02kg",
      "Morango c/ Amora 1,02kg",
      "Morango c/ Frutas Vermelhas 1,02kg",
      "Acerola 1,02kg"
    ],
    "prato-fino": [
      "Arroz Branco 1kg",
      "Arroz Branco 5kg",
      "Arroz Parbolizado 1kg",
      "Arroz Parbolizado 5kg",
      "Arroz Integral 1kg"
    ],
    "vovo-clara": [
      "Biscoito Tradicional 90G",
      "Salgadinhos Buen Apetit Pimenta 100G",
      "Salgadinhos Buen Apetit Bacon 100G",
      "Salgadinhos Buen Apetit Pele 70G",
      "Biscoito Bolinha 150G",
      "Biscoito Argola 150G"
    ],
    "serta-norte": [
      "Queijo Coalho Espeto Tradicional",
      "Queijo Coalho Espeto Orégano",
      "Queijo Coalho Espeto Sem Lactose",
      "Queijo Minas Meia Cura",
      "Queijo Minas Padrão",
      "Queijo Provolone 400G",
      "Manteiga Ghee Tradicional 200G",
      "Queijo Parmesão Ralado 1KG",
      "Manteiga de Garrafa"
    ],
    "ipanema": [
      "Queijo Gouda Fatiado 160G",
      "Cream Cheese Ipanema 1,2KG",
      "Queijo Provolonete 400G",
      "Queijo Prato Fatiado 160G",
      "Queijo Cheddar Fatiado 500G",
      "Ricota Fresca 400G",
      "Queijo Mussarela Fatiada 400G",
      "Queijo Coalho 1KG",
      "Manteiga Pote Sem Sal Ipanema 200G",
      "Queijo Provolone 700G",
      "Queijo Prato Ipanema Peça 2KG",
      "Queijo Mussarela Fatiada 1KG",
      "Queijo Ralado Parmesão Fino 50G",
      "Queijo Ralado 500G",
      "Queijo Fondue 400G",
      "Queijo Coalho Espeto Tradicional",
      "Queijo Montanhes Fracionado",
      "Queijo Prato Mini 500G",
      "Queijo Prato Fatiado 1KG",
      "Queijo Parmesao Fracionado 250G",
      "Queijo Minas Padrão Fracionado 400G",
      "Queijo Minas Frescal 500G",
      "Queijo Mussarela Mini 500G",
      "Queijo Mussarela Ipanema Peça 2KG",
      "Queijo Prato Fatiado 400G",
      "Queijo Coalho Espeto Chimichurri",
      "Queijo Mussarela S/Lactose Fatiada 160G",
      "Queijo Prato Esférico Fracionado 200G",
      "Queijo Mussarela Fatiada 160G",
      "Queijo Ralado Parmesão Grosso 50G",
      "Manteiga Pote Com Sal Ipanema 200G"
    ]
  },
  "atacadao": {
    "capricche": [
      "Cookies Baunilha 60G",
      "Cookies Chocolate 60G",
      "Cookies Brownie 60G",
      "Cookies Festa 60G",
      "Cookies Black 60G",
      "Banalíssima 75G",
      "Banalíssima 38G",
      "Goiabíssima 75G",
      "Goiabíssima 38G",
      "Futurinhos Wafer Chocolate 35G",
      "Futurinhos Wafer Morango 35G",
      "Futurinhos Wafer Laranja 35G",
      "Futurinhos Wafer Abacaxi 35G",
      "Mamma Mia Cracker Original 350G",
      "Mamma Mia Cracker Fibras 350G",
      "Mamma Mia Cracker Gergelim 350G",
      "Mamma Mia Recheado Pizza 108G",
      "Mama Mia Recheado Peito de Peru 108G",
      "Mama Mia Recheado Queijo/Tomate 108G",
      "Mama Mia Recheado Cebola/Salsa 108G",
      "Amanteigado Coco 24G",
      "Amanteigado Coco 330G",
      "Amanteigado Leite 24G",
      "Amanteigado Leite 330G",
      "Amanteigado Chocolate 24G",
      "Amanteigado Chocolate 330G",
      "Amanteigado Kids 24G",
      "Biscoito Capriche Maizena 312G",
      "Biscoito Capriche Maria 312G",
      "Cerelicia Leite/Cereais 110G",
      "Cerelicia Leite/Cereais 24G",
      "Cerelicia Cacau/Mel 110G",
      "Cerelicia Cacau/Mel 24G",
      "Biscoito Capriche Cerelicia Cacau/Cereais 110G",
      "Biscoito Capriche Cerelicia Cacau/Cereais 24G",
      "Biscoito Futurinhos Recheado Black 32G",
      "Biscoito Futurinhos Recheado Bem Casado 32G",
      "Biscoito Futurinhos Recheado Chocolate 32G",
      "Biscoito Futurinhos Recheado Morango 32G"
    ],
    "original": [
      "Morango 1,02kg",
      "Morango c/ Amora 1,02kg",
      "Acerola 1,02kg"
    ]
  }
}
