{
  "assai": {
    "suinco": [
      "Picanha Temperada Resfriada Suinco",
      "Barriga Temperada Resfriada Suinco",
      "Fraldinha Temperada Resfriada Suinco",
      "Sobrepaleta Temperado Resfriado Suinco",
      "Pernil Temperado Resfriado Suinco",
      "File Mignon Temperado Resfriada Suinco",
      "Linguiça Petisco Suinco",
      "Esbein Joelho Suinco",
      "Lombo Temperado Resfriado Suinco",
      "Bacon Em Cubos Suinco",
      "Bacon Suinco",
      "Bacon Fatiado Suinco 500g",
      "Costela Temperada Resfriada Suinco",
      "Alcatra Temperada Resfriada Suinco"
    ],
    "original": [
      "Morango 1,02kg",
      "Morango c/ Amora 1,02kg",
      "Morango c/ Frutas Vermelhas 1,02kg",
      "Acerola 1,02kg"
    ],
    "prato-fino": [
      "Arroz Branco 1kg",
      "Arroz Branco 5kg",
      "Arroz Parbolizado 1kg",
      "Arroz Parbolizado 5kg",
      "Arroz Integral 1kg"
    ]
  },
  "atacadao": {
    "capricche": [
      "Baunilha 60G",
      "Cookies Chocolate 60G",
      "Cookies Brownie 60G",
      "Cookies Festa 60G",
      "Cookies Black 60G",
      "Banalíssima 75G",
      "Banalíssima 38G",
      "Goiabíssima 75G",
      "Goiabíssima 38G",
      "Futurinhos Wafer Chocolate 80G",
      "Futurinhos Wafer Brigadeiro 80G",
      "Futurinhos Wafer Limão 80G",
      "Futurinhos Wafer Morango 80G",
      "Chokolissímo Wafer Chocolate Ao Leite 90G",
      "Chokolíssimo Wafer Trufa 90G",
      "Chocolíssimo Wafer Chocolate Branco 90G",
      "Chokolíssimo Wafer Meio Amargo 90G",
      "Futurinhos Wafer Chocolate 35G",
      "Futurinhos Wafer Morango 35G",
      "Futurinhos Wafer Laranja 35G",
      "Futurinhos Wafer Abacaxi 35G",
      "Mamma Mia Cracker Original 350G",
      "Mamma Mia Cracker Fibras 350G",
      "Mamma Mia Cracker Gergelim 350G",
      "Mamma Mia Recheado Pizza 108G",
      "Mama Mia Recheado Peito de Peru 108G",
      "Mama Mia Recheado Queijo/Tomate 108G",
      "Mama Mia Recheado Cebola/Salsa 108G",
      "Amanteigado Coco 24G",
      "Amanteigado Coco 330G",
      "Amanteigado Leite 24G",
      "Amanteigado Leite 330G",
      "Amanteigado Chocolate 24G",
      "Amanteigado Chocolate 330G",
      "Amanteigado Kids 24G",
      "Biscoito Capriche Maizena 312G",
      "Biscoito Capriche Maria 312G",
      "Cerelicia Leite/Cereais 110G",
      "Cerelicia Leite/Cereais 24G",
      "Cerelicia Cacau/Mel 110G",
      "Cerelicia Cacau/Mel 24G",
      "Biscoito Capriche Cerelicia Cacau/Cereais 110G",
      "Biscoito Capriche Cerelicia Cacau/Cereais 24G",
      "Biscoito Futurinhos Recheado Black 32G",
      "Biscoito Futurinhos Recheado Bem Casado 32G",
      "Biscoito Futurinhos Recheado Chocolate 32G",
      "Biscoito Futurinhos Recheado Morango 32G"
    ],
    "original": [
      "Morango 1,02kg",
      "Morango c/ Amora 1,02kg",
      "Morango c/ Frutas Vermelhas 1,02kg",
      "Acerola 1,02kg"
    ]
  }
}
